### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [Stas-kun/sprint-10#1]
### Добрый день!

_Отлично_:
- Полностью проходит проверку валидация имя
- Полностью проходит проверку валидация почтового ящика
- Полностью проходит проверку валидация телефона
- Большинство проверок проходит валидация url/ip
___

### Надо исправить:

- В репозитории есть директория, которая не относится к проект - `__MACOSX`. Ее необходимо удалить и добавить в `.gitignore`

- По заданию необходимо создать тег у репозитория. Сейчас тегов нет

- Проходит такой невалидный IP: `http://www.255.255.255.255`

---

**Важно:** после исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на *github.io*.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by Stas-kun** [comment]
Fixed

**Comment by mrprovoker** [comment]
Спасибо за правки. Теперь работа отличная.

---

Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*
